#!/usr/bin/env bash

# convert-slides [file.pptx] [/out/dir/]

# requirements
# convert -- brew install imagemagick
# soffice -- brew cask install libreoffice

# progress
# PPT - OK (convert, soffice)
# KEY - ~  (convert, soffice) - weird formatting...
# Google Slides - X - not working
# see: https://codelabs.developers.google.com/codelabs/slides-api/

full=$(basename -- "$1")
temp="$2/../temp"
base="${full%.*}"
extn="${full##*.}"

mkdir -pv "$2/$temp"
soffice --headless --invisible --convert-to pdf "$full" --outdir "$temp"
convert -density 100 "$temp/$base.pdf" "$2/$base-%04d.jpg"
find "$2" -type f -iname "*$base*jpg"
echo "convert-slides complete."
exit 0
