#!/usr/bin/env bash

# convert-slides [file.ppt] [/out/dir/]

# requirements
# convert -- brew install imagemagick
# soffice -- brew cask install libreoffice

# progress
# PPT - OK (convert, soffice)
# KEY - ~  (convert, soffice) - weird formatting...
# Google Slides - X - not working
# see: https://codelabs.developers.google.com/codelabs/slides-api/

full=$(basename -- "$1")
extn="${full##*.}"
file="${full%.*}"
soffice --headless --invisible --convert-to pdf "$full"
convert -monitor -density 100 "$file.pdf" "$2/$file-%04d.jpg"
echo "convert-slides complete: $1"
exit 0
