#!/usr/bin/env bash

# convert-pdf [file.pdf] [/out/dir]

# requirements
# convert -- brew install imagemagick

full=$(basename -- "$1")
base="${full%.*}"
extn="${full##*.}"
convert -density 100 "$1" "$2/$base-%04d.jpg"
find "$2" -type f -iname "*$base*jpg"
echo "convert-pdf complete."
exit 0
