#!/usr/bin/env zsh

# convert-slides [file.pptx] [/out/dir/]
# will output in /out/dir/images and
# use /out/dir/temp for processing

# requirements
# convert -- brew install imagemagick
# soffice -- brew cask install libreoffice

# progress
# PPT - OK (convert, soffice)
# KEY - ~  (convert, soffice) - weird formatting...
# Google Slides - X - not working
# see: https://codelabs.developers.google.com/codelabs/slides-api/

full=$(basename -- "$1")
images="$2/images"
temp="$2/temp"
base="${full%.*}"
extn="${full##*.}"

mkdir -pv "$temp"
soffice --headless --invisible --convert-to pdf "$full" --outdir "$temp"
convert -density 100 "$temp/$base.pdf" "$images/$base-%04d.png"
find "$temp" -type f -iname "*$base*png"
echo "convert-slides complete."
exit 0
