#!/usr/bin/env bash

# convert-wav [newFile] file1.wav file2.wav ...

# requirements
# sox -- brew install sox

sox "${@:2}" --rate 16k --bits 16 --channels 1 "$1" && \
    echo "$1" && echo "convert-wav complete." && \
    rm -f "$temp1" "$temp2"
