#!/usr/bin/zsh

# Repo location
export SLIDESPECS=/home/jeremy/Code/SlideSpecs/app
# export SLIDESPECS=/Users/jwrnr/Documents/Code/research-slidespecs/app

# Get path for tmux invocation
source /home/jeremy/.zshrc

# Go to app
cd $SLIDESPECS
pwd

# File uploading
export GOOGLE_APPLICATION_CREDENTIALS=$SLIDESPECS/private/slidespecs.json

# periodically update browserlists
meteor npx browserslist@latest --update-db

result=1
while [ $result -ne 0 ]; do
    # from https://stackoverflow.com/questions/71147852/getting-certificate-has-expired-error-while-running-meteor
    export NODE_TLS_REJECT_UNAUTHORIZED=0
    meteor --production 2>&1 | tee -a output.log
    result=${PIPESTATUS[0]}
    if [ $result -ne 0 ]; then
        echo ""
        echo ""
        echo "*****************************************************"
        echo "Date: $(date)"
        echo "Server crashed with exit code $result.  Respawning.."
        echo "*****************************************************"
        echo ""
        echo ""
    fi
done

