#!/usr/bin/env bash

export GOOGLE_APPLICATION_CREDENTIALS=/Users/jwrnr/Code/slidespecs-research/app/private/slidespecs.json

until meteor --production 2>&1 | tee -a output.log; do
    echo "Server crashed with exit code $?.  Respawning.." >&2
    sleep 1
done
