#!/usr/bin/env bash

#export GOOGLE_APPLICATION_CREDENTIALS=/Users/jwrnr/Code/research-slidespecs/app/private/slidespecs.json
export GOOGLE_APPLICATION_CREDENTIALS=/Users/jwrnr/Documents/Code/research-slidespecs/app/private/slidespecs.json

result=1
while [ $result -ne 0 ]; do
    meteor --production 2>&1 | tee -a output.log
    result=${PIPESTATUS[0]}
    if [ $result -ne 0 ]; then
        echo ""
        echo ""
        echo "*****************************************************"
        echo "Date: $(date)"
        echo "Server crashed with exit code $result.  Respawning.."
        echo "*****************************************************"
        echo ""
        echo ""
    fi
done

